from PyQt4 import QtCore, QtGui
from pyqtgraph import GraphicsLayoutWidget

_fromUtf8 = QtCore.QString.fromUtf8


class P300UI(object):
    def __init__(self, main_window):
        main_window.setObjectName(_fromUtf8("main_window"))
        main_window.resize(796, 464)
        self.central_widget = QtGui.QWidget(main_window)
        self.central_widget.setObjectName(_fromUtf8("central_widget"))
        self.horizontal_layout_2 = QtGui.QHBoxLayout(self.central_widget)
        self.horizontal_layout_2.setSpacing(0)
        self.horizontal_layout_2.setMargin(0)
        self.horizontal_layout_2.setObjectName(_fromUtf8("horizontal_layout_2"))
        self.horizontal_layout = QtGui.QHBoxLayout()
        self.horizontal_layout.setSpacing(0)
        self.horizontal_layout.setObjectName(_fromUtf8("horizontal_layout"))
        self.graphics_view = GraphicsLayoutWidget(self.central_widget)
        self.graphics_view.setObjectName(_fromUtf8("graphics_view"))
        self.horizontal_layout.addWidget(self.graphics_view)
        self.progress_bar = QtGui.QProgressBar(self.central_widget)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setOrientation(QtCore.Qt.Vertical)
        self.progress_bar.setObjectName(_fromUtf8("progress_bar"))
        self.horizontal_layout.addWidget(self.progress_bar)
        self.horizontal_layout_2.addLayout(self.horizontal_layout)
        main_window.setCentralWidget(self.central_widget)
        self.menu_bar = QtGui.QMenuBar(main_window)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 796, 25))
        self.menu_bar.setObjectName(_fromUtf8("menu_bar"))
        self.menu_calibration = QtGui.QMenu(self.menu_bar)
        self.menu_calibration.setObjectName(_fromUtf8("menu_calibration"))
        self.menu_compute_profile = QtGui.QMenu(self.menu_calibration)
        self.menu_compute_profile.setObjectName(_fromUtf8("menu_compute_profile"))
        self.menu_online_mode = QtGui.QMenu(self.menu_bar)
        self.menu_online_mode.setObjectName(_fromUtf8("menu_online_mode"))
        main_window.setMenuBar(self.menu_bar)
        self.status_bar = QtGui.QStatusBar(main_window)
        self.status_bar.setObjectName(_fromUtf8("status_bar"))
        main_window.setStatusBar(self.status_bar)
        self.action_start_calibration = QtGui.QAction(main_window)
        self.action_start_calibration.setObjectName(_fromUtf8("action_start_calibration"))
        self.action_stop_calibration = QtGui.QAction(main_window)
        self.action_stop_calibration.setObjectName(_fromUtf8("action_stop_calibration"))
        self.action_saved_p300_profile = QtGui.QAction(main_window)
        self.action_saved_p300_profile.setObjectName(_fromUtf8("action_user_p300_profile"))
        self.action_new_p300_profile = QtGui.QAction(main_window)
        self.action_new_p300_profile.setObjectName(_fromUtf8("action_new_p300_profile"))
        self.action_start_online_mode = QtGui.QAction(main_window)
        self.action_start_online_mode.setObjectName(_fromUtf8("action_start_online_mode"))
        self.action_stop_online_mode = QtGui.QAction(main_window)
        self.action_stop_online_mode.setObjectName(_fromUtf8("action_stop_online_mode"))
        self.menu_compute_profile.addAction(self.action_new_p300_profile)
        self.menu_compute_profile.addAction(self.action_saved_p300_profile)
        self.menu_calibration.addAction(self.action_start_calibration)
        self.menu_calibration.addAction(self.action_stop_calibration)
        self.menu_calibration.addAction(self.menu_compute_profile.menuAction())
        self.menu_online_mode.addAction(self.action_start_online_mode)
        self.menu_online_mode.addAction(self.action_stop_online_mode)
        self.menu_bar.addAction(self.menu_calibration.menuAction())
        self.menu_bar.addAction(self.menu_online_mode.menuAction())

        self.retranslate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        main_window.setWindowTitle(QtGui.QApplication.translate("main_window", "Memory Game", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_calibration.setTitle(QtGui.QApplication.translate("main_window", "Calibration", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_compute_profile.setTitle(QtGui.QApplication.translate("main_window", "Compute", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_online_mode.setTitle(QtGui.QApplication.translate("main_window", "Online mode", None, QtGui.QApplication.UnicodeUTF8))
        self.action_start_calibration.setText(QtGui.QApplication.translate("main_window", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.action_stop_calibration.setText(QtGui.QApplication.translate("main_window", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.action_saved_p300_profile.setText(QtGui.QApplication.translate("main_window", "Saved p300 profile", None, QtGui.QApplication.UnicodeUTF8))
        self.action_new_p300_profile.setText(QtGui.QApplication.translate("main_window", "New p300 profile", None, QtGui.QApplication.UnicodeUTF8))
        self.action_start_online_mode.setText(QtGui.QApplication.translate("main_window", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.action_stop_online_mode.setText(QtGui.QApplication.translate("main_window", "Stop", None, QtGui.QApplication.UnicodeUTF8))
